// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BDSpotComInst.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ConfigChange_Confirm;
@class ConfigChange_Request;
@class RedDotInfo;
@class RemoveCache_Confirm;
@class RemoveCache_Request;
@class ReportDevInfo_Confirm;
@class ReportDevInfo_Request;
@class ReportSpotUpdateTime_Confirm;
@class ReportSpotUpdateTime_Request;
@class ResetReq_Confirm;
@class ResetReq_Request;
@class ResponseChatMessage_Confirm;
@class ResponseChatMessage_Request;
@class ResponseOrderStatusChange_Confirm;
@class ResponseOrderStatusChange_Request;
@class ResponseRedDotInfo_Confirm;
@class ResponseRedDotInfo_Request;
@class SetWill_Confirm;
@class SetWill_Request;
@class SpotInfoChange_Confirm;
@class SpotInfoChange_Request;
@class SpotStatusChange_Confirm;
@class SpotStatusChange_Request;
@class UserInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum MSG

typedef GPB_ENUM(MSG) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  MSG_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 0-10:服务占用 */
  MSG_MsgPlaceholder = 0,

  /** 清除本地缓存（服务端发起 针对单个设备） */
  MSG_MsgRemoveCache = 1,

  /** 重启请求包（服务端发起 针对单个设备） */
  MSG_MsgResetReq = 2,

  /** 客户端已经下线（服务端发起 针对单个设备） */
  MSG_MsgSetWill = 3,

  /** 11-20 站点相关 */
  MSG_MsgSpotStatusChange = 11,

  /** 站点信息改变(服务端发起 广播) */
  MSG_MsgSpotInfoChange = 12,

  /** 客户端上报本地站点最新一次的更新时间 服务器下发站点下载包地址（客户端发起） */
  MSG_MsgReportSpotUpdateTime = 13,

  /** 21-30 私信相关 */
  MSG_MsgResponseChatMessageChange = 21,

  /** 31-40 消息标记 */
  MSG_MsgResponseRedDotInfo = 31,

  /** 41-50 订单状态 */
  MSG_MsgResponseOrderStatusChange = 41,

  /** 51-60 上报用户登录、设备基本属性 */
  MSG_MsgReportUserLogout = 51,

  /** 61-70 配置相关 */
  MSG_MsgConfigChange = 61,
};

GPBEnumDescriptor *MSG_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MSG_IsValidValue(int32_t value);

#pragma mark - Enum NOTICE

/** 消息类型 */
typedef GPB_ENUM(NOTICE) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  NOTICE_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位（语法要求） */
  NOTICE_NoticePlaceholder = 0,

  /** 系统通知（普通） */
  NOTICE_NoticeSystem = 1,

  /** 粉丝 */
  NOTICE_NoticeFans = 2,

  /** 动态 */
  NOTICE_NoticeTimeline = 3,

  /** 新增站点 */
  NOTICE_NoticeNewspot = 4,

  /** \@我的消息数量 */
  NOTICE_NoticeAtme = 5,

  /** 私信数量 */
  NOTICE_NoticeLetter = 6,

  /** 社区消息数量 */
  NOTICE_NoticeSocial = 7,

  /** 消息中心数量 */
  NOTICE_NoticeMessageCenter = 8,
};

GPBEnumDescriptor *NOTICE_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NOTICE_IsValidValue(int32_t value);

#pragma mark - BdspotComInstRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface BdspotComInstRoot : GPBRootObject
@end

#pragma mark - Base

typedef GPB_ENUM(Base_FieldNumber) {
  Base_FieldNumber_Cmd = 1,
  Base_FieldNumber_Timestamp = 2,
  Base_FieldNumber_DevId = 3,
  Base_FieldNumber_Payload = 4,
};

/**
 * ------------
 * 通讯消息载体结构体
 * ------------start
 **/
@interface Base : GPBMessage

/** MSG 枚举 */
@property(nonatomic, readwrite) int32_t cmd;

/** 时间戳 后台可使用此字段和上面的cmd字段组成一个64bit的unique id */
@property(nonatomic, readwrite) int32_t timestamp;

/** 设备ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *devId;

/** 存放各种不同类型的消息序列化后的字符串 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *payload;

@end

#pragma mark - SpotStatusChange

typedef GPB_ENUM(SpotStatusChange_FieldNumber) {
  SpotStatusChange_FieldNumber_Req = 1,
  SpotStatusChange_FieldNumber_Conf = 2,
};

/**
 * ------------
 * 后台发起的指令
 * ------------start
 * 站点状态改变
 **/
@interface SpotStatusChange : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) SpotStatusChange_Request *req;
/** Test to see if @c req has been set. */
@property(nonatomic, readwrite) BOOL hasReq;

@property(nonatomic, readwrite, strong, null_resettable) SpotStatusChange_Confirm *conf;
/** Test to see if @c conf has been set. */
@property(nonatomic, readwrite) BOOL hasConf;

@end

#pragma mark - SpotStatusChange_Request

typedef GPB_ENUM(SpotStatusChange_Request_FieldNumber) {
  SpotStatusChange_Request_FieldNumber_SpotId = 1,
  SpotStatusChange_Request_FieldNumber_Status = 2,
  SpotStatusChange_Request_FieldNumber_UpdateTime = 3,
};

@interface SpotStatusChange_Request : GPBMessage

/** 站点ID */
@property(nonatomic, readwrite) int64_t spotId;

/** 充电点状态 */
@property(nonatomic, readwrite) int32_t status;

/** 更新时间戳 */
@property(nonatomic, readwrite) int32_t updateTime;

@end

#pragma mark - SpotStatusChange_Confirm

typedef GPB_ENUM(SpotStatusChange_Confirm_FieldNumber) {
  SpotStatusChange_Confirm_FieldNumber_Status = 1,
};

@interface SpotStatusChange_Confirm : GPBMessage

/** 0接受命令 非0错误命令 */
@property(nonatomic, readwrite) int32_t status;

@end

#pragma mark - SpotInfoChange

typedef GPB_ENUM(SpotInfoChange_FieldNumber) {
  SpotInfoChange_FieldNumber_Req = 1,
  SpotInfoChange_FieldNumber_Conf = 2,
};

/**
 * 站点信息改变
 **/
@interface SpotInfoChange : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) SpotInfoChange_Request *req;
/** Test to see if @c req has been set. */
@property(nonatomic, readwrite) BOOL hasReq;

@property(nonatomic, readwrite, strong, null_resettable) SpotInfoChange_Confirm *conf;
/** Test to see if @c conf has been set. */
@property(nonatomic, readwrite) BOOL hasConf;

@end

#pragma mark - SpotInfoChange_Request

@interface SpotInfoChange_Request : GPBMessage

@end

#pragma mark - SpotInfoChange_Confirm

typedef GPB_ENUM(SpotInfoChange_Confirm_FieldNumber) {
  SpotInfoChange_Confirm_FieldNumber_Status = 1,
};

@interface SpotInfoChange_Confirm : GPBMessage

/** 0接受命令 非0错误命令 */
@property(nonatomic, readwrite) int32_t status;

@end

#pragma mark - ResponseChatMessage

typedef GPB_ENUM(ResponseChatMessage_FieldNumber) {
  ResponseChatMessage_FieldNumber_Req = 1,
  ResponseChatMessage_FieldNumber_Conf = 2,
};

/**
 * 有新私信
 **/
@interface ResponseChatMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ResponseChatMessage_Request *req;
/** Test to see if @c req has been set. */
@property(nonatomic, readwrite) BOOL hasReq;

@property(nonatomic, readwrite, strong, null_resettable) ResponseChatMessage_Confirm *conf;
/** Test to see if @c conf has been set. */
@property(nonatomic, readwrite) BOOL hasConf;

@end

#pragma mark - ResponseChatMessage_Request

typedef GPB_ENUM(ResponseChatMessage_Request_FieldNumber) {
  ResponseChatMessage_Request_FieldNumber_ChatNum = 1,
};

@interface ResponseChatMessage_Request : GPBMessage

/** 未读私信数量 本次协议暂不使用 */
@property(nonatomic, readwrite) int32_t chatNum;

@end

#pragma mark - ResponseChatMessage_Confirm

typedef GPB_ENUM(ResponseChatMessage_Confirm_FieldNumber) {
  ResponseChatMessage_Confirm_FieldNumber_Status = 1,
};

@interface ResponseChatMessage_Confirm : GPBMessage

/** 0接受命令 非0错误命令 */
@property(nonatomic, readwrite) int32_t status;

@end

#pragma mark - ResponseOrderStatusChange

typedef GPB_ENUM(ResponseOrderStatusChange_FieldNumber) {
  ResponseOrderStatusChange_FieldNumber_Req = 1,
  ResponseOrderStatusChange_FieldNumber_Conf = 2,
};

/**
 * 订单状态改变
 **/
@interface ResponseOrderStatusChange : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ResponseOrderStatusChange_Request *req;
/** Test to see if @c req has been set. */
@property(nonatomic, readwrite) BOOL hasReq;

@property(nonatomic, readwrite, strong, null_resettable) ResponseOrderStatusChange_Confirm *conf;
/** Test to see if @c conf has been set. */
@property(nonatomic, readwrite) BOOL hasConf;

@end

#pragma mark - ResponseOrderStatusChange_Request

typedef GPB_ENUM(ResponseOrderStatusChange_Request_FieldNumber) {
  ResponseOrderStatusChange_Request_FieldNumber_OrderId = 1,
};

@interface ResponseOrderStatusChange_Request : GPBMessage

/** 状态改变的订单 本次协议暂不使用 */
@property(nonatomic, readwrite) int64_t orderId;

@end

#pragma mark - ResponseOrderStatusChange_Confirm

typedef GPB_ENUM(ResponseOrderStatusChange_Confirm_FieldNumber) {
  ResponseOrderStatusChange_Confirm_FieldNumber_Status = 1,
};

@interface ResponseOrderStatusChange_Confirm : GPBMessage

/** 0接受命令 非0错误命令 */
@property(nonatomic, readwrite) int32_t status;

@end

#pragma mark - RedDotInfo

typedef GPB_ENUM(RedDotInfo_FieldNumber) {
  RedDotInfo_FieldNumber_Type = 1,
  RedDotInfo_FieldNumber_Num = 2,
};

/**
 * 消息红点结构体
 **/
@interface RedDotInfo : GPBMessage

/** 消息类型 */
@property(nonatomic, readwrite) NOTICE type;

/** 数量 */
@property(nonatomic, readwrite) int32_t num;

@end

/**
 * Fetches the raw value of a @c RedDotInfo's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t RedDotInfo_Type_RawValue(RedDotInfo *message);
/**
 * Sets the raw value of an @c RedDotInfo's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetRedDotInfo_Type_RawValue(RedDotInfo *message, int32_t value);

#pragma mark - ResponseRedDotInfo

typedef GPB_ENUM(ResponseRedDotInfo_FieldNumber) {
  ResponseRedDotInfo_FieldNumber_Req = 1,
  ResponseRedDotInfo_FieldNumber_Conf = 2,
};

/**
 * 消息数量
 **/
@interface ResponseRedDotInfo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ResponseRedDotInfo_Request *req;
/** Test to see if @c req has been set. */
@property(nonatomic, readwrite) BOOL hasReq;

@property(nonatomic, readwrite, strong, null_resettable) ResponseRedDotInfo_Confirm *conf;
/** Test to see if @c conf has been set. */
@property(nonatomic, readwrite) BOOL hasConf;

@end

#pragma mark - ResponseRedDotInfo_Request

typedef GPB_ENUM(ResponseRedDotInfo_Request_FieldNumber) {
  ResponseRedDotInfo_Request_FieldNumber_RedDotInfo = 1,
};

@interface ResponseRedDotInfo_Request : GPBMessage

/** 消息数量详情 */
@property(nonatomic, readwrite, strong, null_resettable) RedDotInfo *redDotInfo;
/** Test to see if @c redDotInfo has been set. */
@property(nonatomic, readwrite) BOOL hasRedDotInfo;

@end

#pragma mark - ResponseRedDotInfo_Confirm

typedef GPB_ENUM(ResponseRedDotInfo_Confirm_FieldNumber) {
  ResponseRedDotInfo_Confirm_FieldNumber_Status = 1,
};

@interface ResponseRedDotInfo_Confirm : GPBMessage

/** 0接受命令 非0错误命令 */
@property(nonatomic, readwrite) int32_t status;

@end

#pragma mark - RemoveCache

typedef GPB_ENUM(RemoveCache_FieldNumber) {
  RemoveCache_FieldNumber_Req = 1,
  RemoveCache_FieldNumber_Conf = 2,
};

/**
 * 清除本地缓存
 **/
@interface RemoveCache : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RemoveCache_Request *req;
/** Test to see if @c req has been set. */
@property(nonatomic, readwrite) BOOL hasReq;

@property(nonatomic, readwrite, strong, null_resettable) RemoveCache_Confirm *conf;
/** Test to see if @c conf has been set. */
@property(nonatomic, readwrite) BOOL hasConf;

@end

#pragma mark - RemoveCache_Request

@interface RemoveCache_Request : GPBMessage

@end

#pragma mark - RemoveCache_Confirm

typedef GPB_ENUM(RemoveCache_Confirm_FieldNumber) {
  RemoveCache_Confirm_FieldNumber_Status = 1,
};

@interface RemoveCache_Confirm : GPBMessage

/** 0接受命令 非0错误命令 */
@property(nonatomic, readwrite) int32_t status;

@end

#pragma mark - ResetReq

typedef GPB_ENUM(ResetReq_FieldNumber) {
  ResetReq_FieldNumber_Req = 1,
  ResetReq_FieldNumber_Conf = 2,
};

/**
 * 重启App
 **/
@interface ResetReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ResetReq_Request *req;
/** Test to see if @c req has been set. */
@property(nonatomic, readwrite) BOOL hasReq;

@property(nonatomic, readwrite, strong, null_resettable) ResetReq_Confirm *conf;
/** Test to see if @c conf has been set. */
@property(nonatomic, readwrite) BOOL hasConf;

@end

#pragma mark - ResetReq_Request

@interface ResetReq_Request : GPBMessage

@end

#pragma mark - ResetReq_Confirm

typedef GPB_ENUM(ResetReq_Confirm_FieldNumber) {
  ResetReq_Confirm_FieldNumber_Status = 1,
};

@interface ResetReq_Confirm : GPBMessage

/** 0接受命令 非0错误命令 */
@property(nonatomic, readwrite) int32_t status;

@end

#pragma mark - ConfigChange

typedef GPB_ENUM(ConfigChange_FieldNumber) {
  ConfigChange_FieldNumber_Req = 1,
  ConfigChange_FieldNumber_Conf = 2,
};

/**
 * 配置文件有更新
 **/
@interface ConfigChange : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ConfigChange_Request *req;
/** Test to see if @c req has been set. */
@property(nonatomic, readwrite) BOOL hasReq;

@property(nonatomic, readwrite, strong, null_resettable) ConfigChange_Confirm *conf;
/** Test to see if @c conf has been set. */
@property(nonatomic, readwrite) BOOL hasConf;

@end

#pragma mark - ConfigChange_Request

@interface ConfigChange_Request : GPBMessage

@end

#pragma mark - ConfigChange_Confirm

typedef GPB_ENUM(ConfigChange_Confirm_FieldNumber) {
  ConfigChange_Confirm_FieldNumber_Status = 1,
};

@interface ConfigChange_Confirm : GPBMessage

/** 0接受命令 非0错误命令 */
@property(nonatomic, readwrite) int32_t status;

@end

#pragma mark - SetWill

typedef GPB_ENUM(SetWill_FieldNumber) {
  SetWill_FieldNumber_Req = 1,
  SetWill_FieldNumber_Conf = 2,
};

/**
 * -------------
 * app端发起的命令
 * -------------start
 * 客户端断块连接（设置setwill来实现）
 **/
@interface SetWill : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) SetWill_Request *req;
/** Test to see if @c req has been set. */
@property(nonatomic, readwrite) BOOL hasReq;

@property(nonatomic, readwrite, strong, null_resettable) SetWill_Confirm *conf;
/** Test to see if @c conf has been set. */
@property(nonatomic, readwrite) BOOL hasConf;

@end

#pragma mark - SetWill_Request

@interface SetWill_Request : GPBMessage

@end

#pragma mark - SetWill_Confirm

typedef GPB_ENUM(SetWill_Confirm_FieldNumber) {
  SetWill_Confirm_FieldNumber_Status = 1,
};

@interface SetWill_Confirm : GPBMessage

/** 0接受命令 非0错误命令 */
@property(nonatomic, readwrite) int32_t status;

@end

#pragma mark - ReportSpotUpdateTime

typedef GPB_ENUM(ReportSpotUpdateTime_FieldNumber) {
  ReportSpotUpdateTime_FieldNumber_Req = 1,
  ReportSpotUpdateTime_FieldNumber_Conf = 2,
};

/**
 * 上一次更新压缩包时间
 **/
@interface ReportSpotUpdateTime : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ReportSpotUpdateTime_Request *req;
/** Test to see if @c req has been set. */
@property(nonatomic, readwrite) BOOL hasReq;

@property(nonatomic, readwrite, strong, null_resettable) ReportSpotUpdateTime_Confirm *conf;
/** Test to see if @c conf has been set. */
@property(nonatomic, readwrite) BOOL hasConf;

@end

#pragma mark - ReportSpotUpdateTime_Request

typedef GPB_ENUM(ReportSpotUpdateTime_Request_FieldNumber) {
  ReportSpotUpdateTime_Request_FieldNumber_UpdateTime = 1,
};

@interface ReportSpotUpdateTime_Request : GPBMessage

/** 更新时间戳 */
@property(nonatomic, readwrite) int32_t updateTime;

@end

#pragma mark - ReportSpotUpdateTime_Confirm

typedef GPB_ENUM(ReportSpotUpdateTime_Confirm_FieldNumber) {
  ReportSpotUpdateTime_Confirm_FieldNumber_URL = 1,
  ReportSpotUpdateTime_Confirm_FieldNumber_Packages = 2,
  ReportSpotUpdateTime_Confirm_FieldNumber_Sign = 3,
  ReportSpotUpdateTime_Confirm_FieldNumber_UpdateTime = 4,
  ReportSpotUpdateTime_Confirm_FieldNumber_IsFirst = 5,
};

@interface ReportSpotUpdateTime_Confirm : GPBMessage

/** 下载地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

/** 包名 英文逗号分隔 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *packages;

/** mdg校验值 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

/** 更新时间戳 */
@property(nonatomic, readwrite) int32_t updateTime;

/** 是否新包 1是 0否 */
@property(nonatomic, readwrite) int32_t isFirst;

@end

#pragma mark - UserInfo

typedef GPB_ENUM(UserInfo_FieldNumber) {
  UserInfo_FieldNumber_Uid = 1,
};

/**
 * 用户详情结构体
 **/
@interface UserInfo : GPBMessage

/** 用户id */
@property(nonatomic, readwrite) int64_t uid;

@end

#pragma mark - ReportDevInfo

typedef GPB_ENUM(ReportDevInfo_FieldNumber) {
  ReportDevInfo_FieldNumber_Req = 1,
  ReportDevInfo_FieldNumber_Conf = 2,
};

/**
 * 上报用户信息 设备信息
 **/
@interface ReportDevInfo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ReportDevInfo_Request *req;
/** Test to see if @c req has been set. */
@property(nonatomic, readwrite) BOOL hasReq;

@property(nonatomic, readwrite, strong, null_resettable) ReportDevInfo_Confirm *conf;
/** Test to see if @c conf has been set. */
@property(nonatomic, readwrite) BOOL hasConf;

@end

#pragma mark - ReportDevInfo_Request

typedef GPB_ENUM(ReportDevInfo_Request_FieldNumber) {
  ReportDevInfo_Request_FieldNumber_Userinfo = 1,
};

@interface ReportDevInfo_Request : GPBMessage

/** 用户信息 */
@property(nonatomic, readwrite, strong, null_resettable) UserInfo *userinfo;
/** Test to see if @c userinfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserinfo;

@end

#pragma mark - ReportDevInfo_Confirm

typedef GPB_ENUM(ReportDevInfo_Confirm_FieldNumber) {
  ReportDevInfo_Confirm_FieldNumber_Status = 1,
};

@interface ReportDevInfo_Confirm : GPBMessage

/** 0接受命令 非0错误命令 */
@property(nonatomic, readwrite) int32_t status;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
